import { GradientText } from "@/components/ui/gradient-text";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - AnsiPress",
  description:
    "Learn how AnsiPress collects, uses, and protects your personal information. Covers both BYOS and Fully Managed hosting services.",
};

const toc = [
  { id: "definitions", label: "1. Definitions" },
  { id: "information-we-collect", label: "2. Information We Collect" },
  { id: "how-we-use", label: "3. How We Use Your Information" },
  { id: "storage-protection", label: "4. How We Store and Protect Your Data" },
  { id: "third-party", label: "5. Third-Party Services" },
  { id: "cookies", label: "6. Cookies and Tracking" },
  { id: "data-retention", label: "7. Data Retention" },
  { id: "your-rights", label: "8. Your Rights" },
  { id: "international-transfers", label: "9. International Data Transfers" },
  { id: "childrens-privacy", label: "10. Children's Privacy" },
  { id: "policy-changes", label: "11. Changes to This Policy" },
  { id: "contact", label: "12. Contact Us" },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-black text-white py-24 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-10">
          <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-3">
            <GradientText>AnsiPress</GradientText>{" "}
            <span className="text-white">Privacy Policy</span>
          </h1>
          <p className="text-zinc-400">Effective Date: March 17, 2026</p>
          <p className="text-zinc-300 mt-4 leading-relaxed">
            AnsiPress (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is committed to protecting your
            privacy. This Privacy Policy explains how we collect, use, and
            safeguard your information when you use the AnsiPress server
            management platform, including our BYOS (Bring Your Own Server) and
            Fully Managed service models.
          </p>
        </div>

        {/* Table of Contents */}
        <div className="rounded-lg border border-white/10 bg-white/5 p-6 mb-10">
          <h2 className="text-white font-semibold text-lg mb-4">
            Table of Contents
          </h2>
          <ol className="space-y-1">
            {toc.map((item) => (
              <li key={item.id}>
                <a
                  href={`#${item.id}`}
                  className="text-purple-400 hover:text-purple-300 underline text-sm"
                >
                  {item.label}
                </a>
              </li>
            ))}
          </ol>
        </div>

        <div className="space-y-12">
          {/* 1. Definitions */}
          <section id="definitions" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              1. Definitions
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 space-y-3 text-zinc-300">
              <p>
                <span className="text-white font-medium">BYOS (Bring Your Own Server)</span>
                {" "}— A service model where you connect your own server (e.g., AWS EC2,
                Hetzner VPS, DigitalOcean Droplet) to AnsiPress. AnsiPress
                manages the software stack via SSH using an SSH key generated by
                AnsiPress and installed on your server.
              </p>
              <p>
                <span className="text-white font-medium">Fully Managed</span>
                {" "}— A service model where AnsiPress provisions and manages
                servers on AnsiPress-owned cloud provider accounts using
                Terraform/OpenTofu. You pay one unified bill (infrastructure +
                management). You do not provide any cloud credentials.
              </p>
              <p>
                <span className="text-white font-medium">Customer Data</span>
                {" "}— Content, files, databases, and application data stored on
                your server(s).
              </p>
              <p>
                <span className="text-white font-medium">Platform Data</span>
                {" "}— Data we collect about how you use AnsiPress, including
                account information, provisioning logs, analytics, and server
                configuration metadata.
              </p>
            </div>
          </section>

          {/* 2. Information We Collect */}
          <section id="information-we-collect" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              2. Information We Collect
            </h2>
            <div className="space-y-6">
              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  Account Information
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>Email address</li>
                  <li>Password (hashed with bcrypt — never stored in plaintext)</li>
                  <li>Full name</li>
                  <li>
                    SSO profile data when you sign in with Google or GitHub
                    (name, email, profile picture, provider ID)
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  Waitlist &amp; Contact Information
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>Email address, name, company name, website URL</li>
                  <li>Use case description and enquiry messages</li>
                  <li>
                    UTM parameters and referral source (for understanding how
                    you found us)
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  BYOS Service Data
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>Server IP address and hostname</li>
                  <li>
                    SSH public key (generated by AnsiPress, installed on your
                    server to enable management)
                  </li>
                  <li>Operating system version and distribution details</li>
                  <li>
                    Provisioning and configuration logs (Ansible playbook
                    execution output)
                  </li>
                  <li>
                    Site configuration metadata (domains, PHP version, SSL
                    status)
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  Fully Managed Service Data
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>
                    Region and server size preferences (you select; AnsiPress
                    provisions on our cloud accounts)
                  </li>
                  <li>Resource usage metrics (CPU, memory, disk)</li>
                  <li>
                    Provisioning logs (Terraform/OpenTofu execution output)
                  </li>
                  <li>Site configuration metadata</li>
                  <li>
                    Note: You do NOT provide cloud provider credentials.
                    AnsiPress owns the cloud accounts.
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  Payment Information
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>
                    Stripe customer ID, subscription status, and billing history
                  </li>
                  <li>
                    Full card numbers are processed exclusively by Stripe. We
                    never store complete card details.
                  </li>
                </ul>
              </div>

              <div className="rounded-lg border border-white/10 bg-white/5 p-6">
                <h3 className="text-white font-semibold mb-3">
                  Automatically Collected Data
                </h3>
                <ul className="list-disc list-inside space-y-1 text-zinc-300">
                  <li>IP address and geolocation (country/region)</li>
                  <li>Browser type, device type, and operating system</li>
                  <li>Pages visited, referrer URLs, and session duration</li>
                  <li>
                    Error data and stack traces via Sentry (for debugging)
                  </li>
                  <li>
                    Anonymised analytics via Vercel Analytics and Speed
                    Insights
                  </li>
                </ul>
              </div>
            </div>
          </section>

          {/* 3. How We Use Your Information */}
          <section id="how-we-use" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              3. How We Use Your Information
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 overflow-hidden">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-white/5 border-b border-white/10">
                    <th className="text-left px-4 py-3 text-white font-semibold">
                      Purpose
                    </th>
                    <th className="text-left px-4 py-3 text-white font-semibold">
                      Legal Basis
                    </th>
                  </tr>
                </thead>
                <tbody className="text-zinc-300">
                  {[
                    ["Provide and operate the platform (account, server management, dashboards)", "Contract performance"],
                    ["Process payments and manage subscriptions", "Contract performance"],
                    ["Send transactional emails (verification, alerts, invoices)", "Contract performance"],
                    ["Respond to support enquiries and contact form submissions", "Legitimate interest"],
                    ["Monitor and debug platform errors (Sentry)", "Legitimate interest"],
                    ["Analyse usage patterns to improve the product (Vercel Analytics)", "Legitimate interest"],
                    ["Enforce acceptable use and prevent fraud", "Legitimate interest / Legal obligation"],
                    ["Send product updates and marketing emails (with opt-out)", "Consent"],
                    ["Comply with legal obligations (tax records, law enforcement requests)", "Legal obligation"],
                  ].map(([purpose, basis], i) => (
                    <tr key={i} className="border-b border-white/10 last:border-0">
                      <td className="px-4 py-3">{purpose}</td>
                      <td className="px-4 py-3 text-zinc-400 whitespace-nowrap">{basis}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* 4. Storage and Protection */}
          <section id="storage-protection" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              4. How We Store and Protect Your Data
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 space-y-3 text-zinc-300">
              <p>We take security seriously. Key measures include:</p>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  <span className="text-white">Database:</span> Neon PostgreSQL
                  with SSL/TLS in transit and AES-256 encryption at rest.
                  Schemas are separated (www, dash, audit) for least-privilege
                  access.
                </li>
                <li>
                  <span className="text-white">Authentication:</span> Passwords
                  hashed with bcrypt. JWT tokens stored in HTTP-only, Secure,
                  SameSite cookies — never in localStorage or sessionStorage.
                </li>
                <li>
                  <span className="text-white">SSH Keys (BYOS):</span> SSH key
                  pairs generated by AnsiPress are stored encrypted. The public
                  key is installed on your server; upon disconnect, the key is
                  revoked and removed.
                </li>
                <li>
                  <span className="text-white">Server Security:</span> Our
                  infrastructure is protected by CrowdSec (intrusion prevention),
                  UFW (firewall), and SSH hardening (key-only auth,
                  non-standard port).
                </li>
                <li>
                  <span className="text-white">Bot &amp; Abuse Protection:</span>{" "}
                  Cloudflare Turnstile on all public forms and Redis-based rate
                  limiting on API endpoints.
                </li>
                <li>
                  <span className="text-white">CORS:</span> API access is
                  restricted to authorised origins only.
                </li>
                <li>
                  <span className="text-white">Payments:</span> Card data is
                  processed by Stripe under their PCI-DSS compliance. We only
                  store non-sensitive Stripe identifiers.
                </li>
              </ul>
            </div>
          </section>

          {/* 5. Third-Party Services */}
          <section id="third-party" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              5. Third-Party Services
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 overflow-hidden">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-white/5 border-b border-white/10">
                    <th className="text-left px-4 py-3 text-white font-semibold">Service</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Purpose</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Privacy Policy</th>
                  </tr>
                </thead>
                <tbody className="text-zinc-300">
                  {[
                    ["Neon", "Managed PostgreSQL database", "https://neon.tech/privacy-policy"],
                    ["Stripe", "Payment processing and billing", "https://stripe.com/privacy"],
                    ["Resend", "Transactional email delivery", "https://resend.com/privacy"],
                    ["Cloudflare", "Turnstile bot protection, CDN", "https://www.cloudflare.com/privacypolicy/"],
                    ["Vercel", "Frontend hosting, analytics, speed insights", "https://vercel.com/legal/privacy-policy"],
                    ["Sentry", "Error tracking and performance monitoring", "https://sentry.io/privacy/"],
                    ["Google", "SSO authentication (optional)", "https://policies.google.com/privacy"],
                    ["GitHub", "SSO authentication (optional)", "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement"],
                    ["Hetzner / AWS / DigitalOcean", "Cloud infrastructure for Fully Managed servers (on AnsiPress-owned accounts)", "Provider-specific policies apply"],
                  ].map(([service, purpose, policy], i) => (
                    <tr key={i} className="border-b border-white/10 last:border-0">
                      <td className="px-4 py-3 text-white font-medium whitespace-nowrap">{service}</td>
                      <td className="px-4 py-3">{purpose}</td>
                      <td className="px-4 py-3">
                        {policy.startsWith("http") ? (
                          <a
                            href={policy}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-purple-400 hover:text-purple-300 underline"
                          >
                            View policy
                          </a>
                        ) : (
                          <span className="text-zinc-400">{policy}</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* 6. Cookies and Tracking */}
          <section id="cookies" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              6. Cookies and Tracking
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 overflow-hidden mb-4">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-white/5 border-b border-white/10">
                    <th className="text-left px-4 py-3 text-white font-semibold">Cookie / Tracker</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Type</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Purpose</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Storage</th>
                  </tr>
                </thead>
                <tbody className="text-zinc-300">
                  {[
                    ["access_token", "Authentication", "Short-lived JWT for authenticated API requests", "HTTP-only, Secure cookie"],
                    ["refresh_token", "Authentication", "Long-lived token to issue new access tokens", "HTTP-only, Secure cookie"],
                    ["cf-turnstile-*", "Security", "Cloudflare Turnstile bot protection on forms", "Session cookie (Cloudflare)"],
                    ["Vercel Analytics", "Analytics", "Anonymised page view and performance data", "No persistent cookie"],
                  ].map(([name, type, purpose, storage], i) => (
                    <tr key={i} className="border-b border-white/10 last:border-0">
                      <td className="px-4 py-3 text-white font-mono text-xs">{name}</td>
                      <td className="px-4 py-3">{type}</td>
                      <td className="px-4 py-3">{purpose}</td>
                      <td className="px-4 py-3 text-zinc-400">{storage}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="text-zinc-400 text-sm">
              We do not use advertising cookies, tracking pixels, or store any
              tokens in localStorage or sessionStorage.
            </p>
          </section>

          {/* 7. Data Retention */}
          <section id="data-retention" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              7. Data Retention
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 overflow-hidden">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-white/5 border-b border-white/10">
                    <th className="text-left px-4 py-3 text-white font-semibold">Data Type</th>
                    <th className="text-left px-4 py-3 text-white font-semibold">Retention Period</th>
                  </tr>
                </thead>
                <tbody className="text-zinc-300">
                  {[
                    ["Account data (email, name, hashed password)", "Until account deletion; up to 90 days in backups thereafter"],
                    ["SSO profile data", "Until account deletion"],
                    ["Waitlist / contact form submissions", "Up to 2 years or until you request deletion"],
                    ["BYOS: Server connection data (IP, hostname, SSH key)", "Retained while server is connected; SSH key revoked and deleted upon disconnect"],
                    ["BYOS: Provisioning logs and site configs", "Up to 1 year after server disconnect"],
                    ["Fully Managed: Server and resource data", "30-day grace period after termination, then servers are decommissioned and all associated data is deleted"],
                    ["Payment records (Stripe IDs, billing history)", "7 years for tax/legal compliance"],
                    ["Analytics data (Vercel)", "Anonymised; subject to Vercel's retention policy"],
                    ["Error logs (Sentry)", "90 days"],
                    ["Audit logs", "1 year"],
                  ].map(([type, period], i) => (
                    <tr key={i} className="border-b border-white/10 last:border-0">
                      <td className="px-4 py-3 font-medium">{type}</td>
                      <td className="px-4 py-3 text-zinc-400">{period}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* 8. Your Rights */}
          <section id="your-rights" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              8. Your Rights
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 space-y-3 text-zinc-300">
              <p>Depending on your jurisdiction, you may have the following rights:</p>
              <ul className="list-disc list-inside space-y-2">
                <li><span className="text-white">Access:</span> Request a copy of the personal data we hold about you.</li>
                <li><span className="text-white">Correction:</span> Request correction of inaccurate or incomplete data.</li>
                <li><span className="text-white">Deletion:</span> Request deletion of your personal data (&ldquo;right to be forgotten&rdquo;).</li>
                <li><span className="text-white">Data Portability:</span> Receive your data in a structured, machine-readable format.</li>
                <li><span className="text-white">Restriction:</span> Request that we restrict processing of your data in certain circumstances.</li>
                <li><span className="text-white">Objection:</span> Object to processing based on legitimate interests.</li>
                <li><span className="text-white">Withdraw Consent:</span> Where processing is based on consent, you may withdraw it at any time.</li>
              </ul>
              <p className="mt-4">
                To exercise any of these rights, email us at{" "}
                <a href="mailto:privacy@ansipress.com" className="text-purple-400 hover:text-purple-300 underline">
                  privacy@ansipress.com
                </a>
                . To unsubscribe from marketing emails, use the unsubscribe link
                in any email or visit{" "}
                <Link href="/unsubscribe" className="text-purple-400 hover:text-purple-300 underline">
                  ansipress.com/unsubscribe
                </Link>
                .
              </p>
            </div>
          </section>

          {/* 9. International Data Transfers */}
          <section id="international-transfers" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              9. International Data Transfers
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 text-zinc-300">
              <p>
                AnsiPress is operated from India. By using our platform, your
                data may be transferred to and processed in countries outside
                your own, including the United States and the European Union,
                where our cloud infrastructure and third-party providers
                operate. We take reasonable steps to ensure that any such
                transfers comply with applicable data protection laws, including
                through the use of standard contractual clauses or equivalent
                safeguards where required.
              </p>
            </div>
          </section>

          {/* 10. Children's Privacy */}
          <section id="childrens-privacy" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              10. Children&apos;s Privacy
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 text-zinc-300">
              <p>
                AnsiPress is not directed at individuals under the age of 18.
                We do not knowingly collect personal data from anyone under 18
                years of age. If you believe we have inadvertently collected
                such data, please contact us at{" "}
                <a href="mailto:privacy@ansipress.com" className="text-purple-400 hover:text-purple-300 underline">
                  privacy@ansipress.com
                </a>{" "}
                and we will promptly delete it.
              </p>
            </div>
          </section>

          {/* 11. Changes to This Policy */}
          <section id="policy-changes" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              11. Changes to This Policy
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 text-zinc-300">
              <p>
                We may update this Privacy Policy from time to time. When we do,
                we will revise the &ldquo;Effective Date&rdquo; at the top of this page and,
                for material changes, notify you via email or a prominent notice
                on the platform. Your continued use of AnsiPress after any
                changes constitutes acceptance of the updated policy.
              </p>
            </div>
          </section>

          {/* 12. Contact Us */}
          <section id="contact" className="scroll-mt-24">
            <h2 className="text-xl font-semibold text-white mb-4">
              12. Contact Us
            </h2>
            <div className="rounded-lg border border-white/10 bg-white/5 p-6 text-zinc-300 space-y-3">
              <p>
                If you have any questions, concerns, or requests regarding this
                Privacy Policy, please contact us:
              </p>
              <ul className="space-y-1">
                <li>
                  <span className="text-white">Email:</span>{" "}
                  <a href="mailto:privacy@ansipress.com" className="text-purple-400 hover:text-purple-300 underline">
                    privacy@ansipress.com
                  </a>
                </li>
                <li>
                  <span className="text-white">Contact form:</span>{" "}
                  <Link href="/contact" className="text-purple-400 hover:text-purple-300 underline">
                    ansipress.com/contact
                  </Link>
                </li>
              </ul>
              <p className="text-zinc-500 text-sm pt-2">
                AnsiPress is operated by AnsiPress.
              </p>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}
